services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    platform: linux/amd64
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD:?MSSQL_SA_PASSWORD must be defined in .env}
      MSSQL_PID: "StandardDeveloper"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '$MSSQL_SA_PASSWORD' -Q \"SELECT 1\" -C || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./backend/ScanityCheck.Api
      args:
        ZAP_VERSION: "${ZAP_VERSION:?ZAP_VERSION must be defined in .env}"
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sql-server;Database=ScanityCheckDb;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True"
      Jwt__Key: ${JWT_KEY:?JWT_KEY must be defined in .env}
      Jwt__Issuer: ScanityCheck
      Jwt__Audience: ScanityCheckUsers
      Jwt__ExpiryMinutes: 120
      ZapSettings__ZapPath: /opt/ZAP_${ZAP_VERSION}/zap.sh
      ZapSettings__Mode: ${ZAP_MODE}
      ZapSettings__ReportsFolder: /reports/zap
    volumes:
      - ./backend/ScanityCheck.Api:/app
      - /app/bin
      - /app/obj
      - ./reports:/reports
    depends_on:
      sql-server:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      target: development    # Change to 'production' later
    # environment:
      # - CHOKIDAR_USEPOLLING=true  # Uncomment this if hot-reload fails
    ports:
      - "5173:5173"          # DEV: Mapping host 5173 to Vite 5173
      # - "80:80"              # PROD: Mapping host 80 to Nginx 80
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    depends_on:
      - api

volumes:
  mssql_data:
  node_modules: